### ISSUE TITLE
Can't install library on local machine

### ISSUE THREAD

**Issue by awa5114** [brendan-ward/pyogrio#3]
Hello.

I have tried to install this experimental library since I am having trouble reading large ESRI geodatabases as indicated in:

https://github.com/geopandas/geopandas/issues/1661

I downloaded the repo as a zip and placed it in the working directory of my own project. I then `cd`ed to the root folder of `pyogrio` and attempted the followin:

`python setup.py develop`

I got a long traceback:

```
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    config = {flag: read_response([gdal_config, f"--{flag}"]) for flag in flags}
  File "setup.py", line 44, in <dictcomp>
    config = {flag: read_response([gdal_config, f"--{flag}"]) for flag in flags}
  File "setup.py", line 19, in read_response
    return subprocess.check_output(cmd).decode("utf").strip()
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\myenv\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\myenv\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\myenv\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\myenv\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I checked in setup.py and it looks like the `GDAL_CONFIG` environment variable is expected, so I tried an echo command:

`echo %GDAL_CONFIG%`

but this reveals that the environment variable is not defined. So then I checked to see whether `gdal` is in my environment with `conda list gdal`. This is what I got:

```
#
# Name                    Version                   Build  Channel
gdal                      3.1.2            py38h5f218aa_3    conda-forge
libgdal                   3.1.2                h586bd2e_3    conda-forge

```

Which looks OK I guess. Then I tried a different environment variable, namely `echo %GDAL_DATA%`. This also seemed OK since I got a path as follows:

`C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\myenv\Library\share\gdal`

Why won't `python setup.py develop` install the library? Thanks....

**Comment by brendan-ward** [comment]
@awa5114 Thanks for your interest in `pyogrio`!

Sorry for the challenges - we haven't yet had a chance to work out all the packaging / installation details compared to more mature libraries like `fiona`.  Unfortunately, I don't have access to a Windows test machine and have not yet had a chance to setup a CI for Windows environments to test build / installation issues.

Since it looks like you are installing from `conda-forge`, would you mind trying to install `pyogrio` from `conda-forge`?  There is a [conda feedstock](https://github.com/conda-forge/pyogrio-feedstock) for it.

If you instead want to try building from source on Windows, I would suggest reviewing the Windows-specific build instructions for `fiona` here: https://github.com/Toblerity/Fiona#windows
It looks like you have to manually specify additional parameters to `setup.py` to point it to the GDAL libraries.

Also, building from source will likely run into incompatibilities with both `shapely` and `fiona` unless all are pointing at system versions of GDAL and GEOS.  These may not immediately present during installation, but will fail with unclear errors when trying to use the library.

I have had success on Docker starting from `osgeo/gdal:ubuntu-small-latest`, installing GEOS via `apt-get`, and then installing `pygeos`, `shapely`, and `fiona` via `pip` with the `--no-binary` option to force building from source against the system GDAL / GEOS.

**Comment by theroggy** [comment]
Hello!
I tried installing from conda-forge on windows the package wasn't found, probably because only osx-64 and linux-64 packages are available? 
https://anaconda.org/conda-forge/pyogrio

**Comment by jorisvandenbossche** [comment]
An update on this: installing from source is now supported on windows (assuming you pass the correct flags to find GDAL, see the README). 
But more importantly, there are now also conda-forge packages available for windows!

**Comment by brendan-ward** [comment]
Many thanks to @jorisvandenbossche for getting the Windows version out on conda-forge!  🎉 

I'm going to close this now, assuming that either building from source on Windows or conda-forge works.  If you run into issues, please reopen this issue or create a new one with a specific error report.
